In [1]:
import pandas as pd

In [2]:
import pandas as pd

df = pd.read_csv("datasets/Titanic-Dataset.csv")
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [3]:
# syntax for loc
#df.loc[row_condition, column_selection]

In [4]:
df[df["Age"]>30]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df.loc[df["Age"] > 30, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
# Passengers who survived
df.loc[df["Survived"] == 1, ["Name","Age","Survived"]]

                                                  Name   Age  Survived
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                               Heikkinen, Miss. Laina  26.0         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0         1
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0         1
..                                                 ...   ...       ...
875                   Najib, Miss. Adele Kiamie "Jane"  15.0         1
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0         1
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0         1
887                       Graham, Miss. Margaret Edith  19.0         1
889                              Behr, Mr. Karl Howell  26.0         1

[342 rows x 3 columns]

In [7]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [8]:
#Passengers in 1st class
df.loc[df["Pclass"]==1,["Name","Age","Pclass","Sex"]]

                                                  Name   Age  Pclass     Sex
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1  female
6                              McCarthy, Mr. Timothy J  54.0       1    male
11                            Bonnell, Miss. Elizabeth  58.0       1  female
23                        Sloper, Mr. William Thompson  28.0       1    male
..                                                 ...   ...     ...     ...
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0       1  female
872                           Carlsson, Mr. Frans Olof  33.0       1    male
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0       1  female
887                       Graham, Miss. Margaret Edith  19.0       1  female
889                              Behr, Mr. Karl Howell  26.0       1    male

[216 rows x 4 columns]

In [9]:
# Age > 30 AND Survived
df.loc[(df["Age"] > 30) & (df["Survived"] == 0), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [10]:
# Age < 18 OR Female
df.loc[(df["Age"] < 18) | (df["Sex"] == "female"), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
# make a 5 question  live and practice

In [11]:
# find out the members numbers  of 3rd class who is female
df.loc[(df["Pclass"]==3) & (df["Sex"]=="female"),["Pclass","Sex","Name"]]

     Pclass     Sex                                               Name
2         3  female                             Heikkinen, Miss. Laina
8         3  female  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10        3  female                    Sandstrom, Miss. Marguerite Rut
14        3  female               Vestrom, Miss. Hulda Amanda Adolfina
18        3  female  Vander Planke, Mrs. Julius (Emelia Maria Vande...
..      ...     ...                                                ...
863       3  female                  Sage, Miss. Dorothy Edith "Dolly"
875       3  female                   Najib, Miss. Adele Kiamie "Jane"
882       3  female                       Dahlberg, Miss. Gerda Ulrika
885       3  female               Rice, Mrs. William (Margaret Norton)
888       3  female           Johnston, Miss. Catherine Helen "Carrie"

[144 rows x 3 columns]

In [12]:
# Female passengers older than 25
df.loc[(df["Sex"] == "female") & (df["Age"] > 25), ["Name", "Age", "Pclass"]]

                                                  Name   Age  Pclass
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1
2                               Heikkinen, Miss. Laina  26.0       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0       3
11                            Bonnell, Miss. Elizabeth  58.0       1
..                                                 ...   ...     ...
866                       Duran y More, Miss. Asuncion  27.0       2
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0       1
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0       2
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0       1
885               Rice, Mrs. William (Margaret Norton)  39.0       3

[139 rows x 3 columns]

In [13]:
# Average age of survivors
df.loc[df["Survived"]==1,"Age"].mean()

np.float64(28.343689655172415)

In [15]:
#Rich passengers (Fare > 100) who survived only find name and age
rich_survivors = df.loc[(df['Fare'] > 100) & (df['Survived'] == 1), ['Name', 'Age']]
print(rich_survivors)

                                                  Name    Age
31      Spencer, Mrs. William Augustus (Marie Eugenie)    NaN
88                          Fortune, Miss. Mabel Helen  23.00
195                               Lurette, Miss. Elise  58.00
215                            Newell, Miss. Madeleine  31.00
258                                   Ward, Miss. Anna  35.00
268      Graham, Mrs. William Thompson (Edith Junkins)  58.00
269                             Bissette, Miss. Amelia  35.00
299    Baxter, Mrs. James (Helene DeLaudeniere Chaput)  50.00
305                     Allison, Master. Hudson Trevor   0.92
306                            Fleming, Miss. Margaret    NaN
307  Penasco y Castellana, Mrs. Victor de Satode (M...  17.00
311                         Ryerson, Miss. Emily Borie  18.00
318                           Wick, Miss. Mary Natalie  31.00
319  Spedden, Mrs. Frederic Oakley (Margaretta Corn...  40.00
325                           Young, Miss. Marie Grice  36.00
334  Frauenthal, Mrs. Henry William (Clara Heinshei...    NaN
337                    Burns, Miss. Elizabeth Margaret  41.00
341                     Fortune, Miss. Alice Elizabeth  24.00
380                              Bidois, Miss. Rosalie  42.00
390                         Carter, Mr. William Ernest  36.00
393                             Newell, Miss. Marjorie  23.00
435                          Carter, Miss. Lucile Polk  14.00
537                                LeRoy, Miss. Bertha  30.00
550                        Thayer, Mr. John Borland Jr  17.00
581  Thayer, Mrs. John Borland (Marian Longstreth M...  39.00
609                          Shutes, Miss. Elizabeth W  40.00
660                      Frauenthal, Dr. Henry William  50.00
679                 Cardeza, Mr. Thomas Drake Martinez  36.00
689                  Madill, Miss. Georgette Alexandra  15.00
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  18.00
708                               Cleaver, Miss. Alice  22.00
716                      Endres, Miss. Caroline Louise  38.00
730                      Allen, Miss. Elisabeth Walton  29.00
737                             Lesurer, Mr. Gustave J  35.00
742              Ryerson, Miss. Susan Parker "Suzette"  21.00
763          Carter, Mrs. William Ernest (Lucile Polk)  36.00
779  Robert, Mrs. Edward Scott (Elisabeth Walton Mc...  43.00
802                Carter, Master. William Thornton II  11.00
856         Wick, Mrs. George Dennick (Mary Hitchcock)  45.00

In [19]:
# find the name and age of Children (<15) in 3rd class
children_3rd_class = df.loc[(df['Age'] < 15) & (df['Pclass'] == 3), ['Name', 'Age']]
print(children_3rd_class)

                                                Name    Age
7                     Palsson, Master. Gosta Leonard   2.00
10                   Sandstrom, Miss. Marguerite Rut   4.00
14              Vestrom, Miss. Hulda Amanda Adolfina  14.00
16                              Rice, Master. Eugene   2.00
24                     Palsson, Miss. Torborg Danira   8.00
39                       Nicola-Yarred, Miss. Jamila  14.00
50                        Panula, Master. Juha Niilo   7.00
59                Goodwin, Master. William Frederick  11.00
63                             Skoog, Master. Harald   4.00
111                             Zabour, Miss. Hileni  14.50
119                Andersson, Miss. Ellis Anna Maria   2.00
125                     Nicola-Yarred, Master. Elias  12.00
147                 Ford, Miss. Robina Maggie "Ruby"   9.00
164                     Panula, Master. Eino Viljami   1.00
165  Goldsmith, Master. Frank John William "Frankie"   9.00
171                             Rice, Master. Arthur   4.00
172                     Johnson, Miss. Eleanor Ileen   1.00
182            Asplund, Master. Clarence Gustaf Hugo   9.00
184              Kink-Heilmann, Miss. Luise Gretchen   4.00
205                       Strom, Miss. Telma Matilda   2.00
233                   Asplund, Miss. Lillian Gertrud   5.00
261                Asplund, Master. Edvin Rojj Felix   3.00
278                               Rice, Master. Eric   7.00
348           Coutts, Master. William Loch "William"   3.00
374                       Palsson, Miss. Stina Viola   3.00
381                      Nakid, Miss. Maria ("Mary")   1.00
386                  Goodwin, Master. Sidney Leonard   1.00
419                        Van Impe, Miss. Catharina  10.00
448                   Baclini, Miss. Marie Catherine   5.00
469                    Baclini, Miss. Helene Barbara   0.75
479                         Hirvonen, Miss. Hildur E   2.00
480                   Goodwin, Master. Harold Victor   9.00
489            Coutts, Master. Eden Leslie "Neville"   9.00
541             Andersson, Miss. Ingeborg Constanzia   9.00
542                Andersson, Miss. Sigrid Elisabeth  11.00
634                               Skoog, Miss. Mabel   9.00
642                    Skoog, Miss. Margit Elizabeth   2.00
644                           Baclini, Miss. Eugenie   0.75
683                      Goodwin, Mr. Charles Edward  14.00
686                         Panula, Mr. Jaako Arnold  14.00
691                               Karun, Miss. Manca   4.00
731                         Hassan, Mr. Houssein G N  11.00
751                              Moor, Master. Meier   6.00
777                    Emanuel, Miss. Virginia Ethel   5.00
780                             Ayoub, Miss. Banoura  13.00
787                        Rice, Master. George Hugh   8.00
788                       Dean, Master. Bertram Vere   1.00
803                  Thomas, Master. Assad Alexander   0.42
813               Andersson, Miss. Ebba Iris Alfrida   6.00
819                     Skoog, Master. Karl Thorsten  10.00
824                     Panula, Master. Urho Abraham   2.00
850          Andersson, Master. Sigvard Harald Elias   4.00
852                          Boulos, Miss. Nourelain   9.00
869                  Johnson, Master. Harold Theodor   4.00

In [22]:
# Count passengers older than 60
df.loc[df["Age"] > 60, :].shape[0]

22

In [26]:
# your task take a another datasets and make a 30 to 50 question and do a practice like this 
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target
df['species'] = df['species'].replace({0:'setosa', 1:'versicolor', 2:'virginica'})

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [27]:
import pandas as pd
from sklearn.datasets import load_wine

wine = load_wine()
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df['target'] = wine.target

# Replace target numbers with names
df['target'] = df['target'].replace({
    0: 'class_0',
    1: 'class_1',
    2: 'class_2'
})

df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,class_0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,class_0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,class_0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,class_0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,class_0