In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'Finance', 'IT'],
'Employee': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
'Salary': [50000, 40000, 55000, 60000, 42000, 65000, 58000],
'Experience': [2, 1, 3, 5, 2, 6, 4]
}


df = pd.DataFrame(data)
df

  Department Employee  Salary  Experience
0         IT        A   50000           2
1         HR        B   40000           1
2         IT        C   55000           3
3    Finance        D   60000           5
4         HR        E   42000           2
5    Finance        F   65000           6
6         IT        G   58000           4

3. What is GroupBy?

groupby() is used to split data into groups, apply a function, and combine results.

Split → Apply → Combine

Basic GroupBy (Single Column)
Group by Department

In [3]:
df.groupby('Department')

In [4]:
df.groupby('Department')['Salary'].mean()
#Calculate Mean Salary per Department

Department
Finance    62500.000000
HR         41000.000000
IT         54333.333333
Name: Salary, dtype: float64

In [5]:
# Multiple Aggregations
df.groupby('Department')['Salary'].agg(['mean', 'max', 'min', 'sum'])

                    mean    max    min     sum
Department
Finance     62500.000000  65000  60000  125000
HR          41000.000000  42000  40000   82000
IT          54333.333333  58000  50000  163000

In [6]:
# GroupBy with Multiple Columns 
df.groupby(['Department', 'Experience'])['Salary'].mean()

Department  Experience
Finance     5             60000.0
            6             65000.0
HR          1             40000.0
            2             42000.0
IT          2             50000.0
            3             55000.0
            4             58000.0
Name: Salary, dtype: float64

In [7]:
df.groupby('Department')['Employee'].count()
#Using GroupBy with Count

Department
Finance    2
HR         2
IT         3
Name: Employee, dtype: int64

In [8]:
def salary_range(x):
 return x.max() - x.min()

df.groupby('Department')['Salary'].apply(salary_range)

Department
Finance    5000
HR         2000
IT         8000
Name: Salary, dtype: int64

In [ ]:
# titanic datasets

In [9]:
import pandas as pd

df = pd.read_csv("datasets/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
#Average Fare per Passenger Class
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [11]:
df.groupby('Sex')['Survived'].mean()
#Survival Rate by Gender

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [12]:
# Multiple Aggregations
df.groupby('Pclass')['Fare'].agg(['mean', 'max', 'min', 'count'])

             mean       max  min  count
Pclass
1       84.154687  512.3292  0.0    216
2       20.662183   73.5000  0.0    184
3       13.675550   69.5500  0.0    491

In [13]:
#GroupBy Multiple Columns
df.groupby(['Pclass', 'Sex'])['Survived'].mean()

Pclass  Sex
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: Survived, dtype: float64

In [14]:
# Average age of survivors vs non-survivors
df.groupby('Survived')['Age'].mean()

Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64

In [15]:
# Count of male and female passengers per class
df.groupby(['Pclass', 'Sex']).size()

Pclass  Sex
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
dtype: int64

In [16]:
df["average age "]=df.groupby("Sex")["Age"].mean()

In [17]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,average age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,NaN
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,NaN
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,NaN
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,NaN
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,NaN
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,NaN

In [18]:
# Which embark town has highest survival rate?

df.groupby("Embarked")["Age"].mean()

Embarked
C    30.814769
Q    28.089286
S    29.445397
Name: Age, dtype: float64

Now your task is to make a 25 question from chatgpt and practcie your self furst write the question and then answer

In [19]:
import pandas as pd

df1 = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['A', 'B', 'C']
})
df1

   id name
0   1    A
1   2    B
2   3    C

In [20]:
df1

   id name
0   1    A
1   2    B
2   3    C

In [21]:
df2 = pd.DataFrame({
    'id': [1, 2, 4],
    'score': [85, 90, 88]
})

In [22]:
df2

   id  score
0   1     85
1   2     90
2   4     88

In [23]:
result = pd.merge(df1, df2, on='id')
print(result)

   id name  score
0   1    A     85
1   2    B     90

In [24]:
pd.merge(df1, df2, on='id', how='inner')
#Keeps common rows only

   id name  score
0   1    A     85
1   2    B     90

In [25]:
# Test with new data
import pandas as pd

students = pd.DataFrame({
    'student_id': [101, 102, 103, 104],
    'student_name': ['Ram', 'Sita', 'Hari', 'Gita'],
    'department': ['CS', 'IT', 'CS', 'BCA']
})

print(students)

   student_id student_name department
0         101          Ram         CS
1         102         Sita         IT
2         103         Hari         CS
3         104         Gita        BCA

In [26]:
marks = pd.DataFrame({
    'student_id': [101, 102, 105],
    'marks': [88, 92, 75]
})

print(marks)

   student_id  marks
0         101     88
1         102     92
2         105     75

In [27]:
inner_join = pd.merge(students, marks, on='student_id', how='inner')
print(inner_join)
# Common records only

   student_id student_name department  marks
0         101          Ram         CS     88
1         102         Sita         IT     92

In [28]:
left_join = pd.merge(students, marks, on='student_id', how='left')
print(left_join)

   student_id student_name department  marks
0         101          Ram         CS   88.0
1         102         Sita         IT   92.0
2         103         Hari         CS    NaN
3         104         Gita        BCA    NaN

In [29]:
right_join = pd.merge(students, marks, on='student_id', how='right')
print(right_join)

   student_id student_name department  marks
0         101          Ram         CS     88
1         102         Sita         IT     92
2         105          NaN        NaN     75

In [30]:
outer_join = pd.merge(students, marks, on='student_id', how='outer')
print(outer_join)
# Outer Join (Everything from both tables)

   student_id student_name department  marks
0         101          Ram         CS   88.0
1         102         Sita         IT   92.0
2         103         Hari         CS    NaN
3         104         Gita        BCA    NaN
4         105          NaN        NaN   75.0

Easy Memory Trick

Inner → common only

Left → everything from first table

Right → everything from second table

Outer → everything from both