### Basic data structures in pandas
pandas provides two types of classes for handling data:

Series: a one-dimensional labeled array holding data of any type
such as integers, strings, Python objects etc.

DataFrame: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

In [2]:
# 1️⃣ Import Pandas Library
# Import pandas to work with DataFrames
import pandas as pd

In [3]:
# 2️⃣ Create a Sample DataFrame
# We will create a DataFrame with columns 'Name', 'Age', 'City'
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar']
}

df = pd.DataFrame(data)  # Create DataFrame
df

      Name  Age        City
0    Alice   25   Kathmandu
1      Bob   30     Pokhara
2  Charlie   35    Lalitpur
3    David   40  Biratnagar

In [4]:
# 3️⃣ Default Index
# By default, Pandas assigns a numeric index starting from 0
print(df.index)  # Shows the default index

RangeIndex(start=0, stop=4, step=1)

In [5]:
# 4️⃣ Set a Column as Index
# You can set any column as index using set_index()
df_name_index = df.set_index('Name')  # Set 'Name' as index (returns new DataFrame)
df_name_index  # Display DataFrame with new index

         Age        City
Name
Alice     25   Kathmandu
Bob       30     Pokhara
Charlie   35    Lalitpur
David     40  Biratnagar

In [6]:
# 5️⃣ Set index inplace (modify original DataFrame)
# Using inplace=True modifies the original DataFrame directly
df.set_index('Name', inplace=True)
print(df)  # Now 'Name' is the index of df

         Age        City
Name
Alice     25   Kathmandu
Bob       30     Pokhara
Charlie   35    Lalitpur
David     40  Biratnagar

In [7]:
df

         Age        City
Name
Alice     25   Kathmandu
Bob       30     Pokhara
Charlie   35    Lalitpur
David     40  Biratnagar

In [8]:
# 6️⃣ Reset Index
# Reset index back to default numeric index
df.reset_index(inplace=True)
df # 'Name' column is back as normal column

      Name  Age        City
0    Alice   25   Kathmandu
1      Bob   30     Pokhara
2  Charlie   35    Lalitpur
3    David   40  Biratnagar

In [9]:
# 7️⃣ Selecting Rows Using Index
# Set 'Name' as index again to select rows using loc
df.set_index('Name', inplace=True)

# Select row with index label 'Alice'
print(df.loc['Alice'])

Age            25
City    Kathmandu
Name: Alice, dtype: object

In [10]:
# 8️⃣ Multiple Indexes (Hierarchical / MultiIndex)
# You can set multiple columns as index for a MultiIndex
df.set_index(['City'])  # MultiIndex with 'Name' and 'City'

            Age
City
Kathmandu    25
Pokhara      30
Lalitpur     35
Biratnagar   40

In [11]:
df

         Age        City
Name
Alice     25   Kathmandu
Bob       30     Pokhara
Charlie   35    Lalitpur
David     40  Biratnagar

### What does inplace=True mean?

- `inplace=True` means **modify the original DataFrame**
- No new DataFrame is created
- Changes happen **permanently**

### Example:
Without inplace:
```python
new_df = df.set_index("Student_ID")

In [12]:
import pandas as pd
# Creating a simple DataFrame
data = {
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

# Display the DataFrame
df

   Student_ID  Name  Marks
0         101   Ram     85
1         102  Sita     90
2         103  Hari     78
3         104  Gita     92

In [13]:
df.set_index("Student_ID", inplace=True)

In [14]:
df

            Name  Marks
Student_ID
101          Ram     85
102         Sita     90
103         Hari     78
104         Gita     92

In [15]:
# Reset index (creates a new DataFrame)
df_reset = df.reset_index()

df_reset

   Student_ID  Name  Marks
0         101   Ram     85
1         102  Sita     90
2         103  Hari     78
3         104  Gita     92

In [16]:
# Reset index permanently
df.reset_index(inplace=True)

df

   Student_ID  Name  Marks
0         101   Ram     85
1         102  Sita     90
2         103  Hari     78
3         104  Gita     92