# Pandas `loc` vs `iloc`
## Detailed Comparison with Examples

In [1]:
import pandas as pd

In [2]:
data = {
    "ID": [101, 102, 103, 104],
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)
df

    ID  Name  Marks
0  101   Ram     85
1  102  Sita     90
2  103  Hari     78
3  104  Gita     92

## `loc` – Label-based Indexing

- `loc` is used to access data using **labels**
- Labels can be:
  - Index names
  - Column names
- **Both start and end values are included**

In [3]:
df.loc[1,"Name"]

'Sita'

In [4]:
df.set_index("ID", inplace=True)
df

     Name  Marks
ID
101   Ram     85
102  Sita     90
103  Hari     78
104  Gita     92

In [5]:
df.iloc[2,1]

np.int64(78)

In [6]:
df.iloc[1,:0]

Series([], Name: 102, dtype: object)

In [7]:
df.loc["Ram"] # access single rows it gets error because we have set index to ID column and Ram is not an index value
#Key Concept
# loc[] works with row labels (index names)
#iloc[] works with row numbers

KeyError: 'Ram'

In [8]:
df.loc[[101, 103]] # access multiple rows

     Name  Marks
ID
101   Ram     85
103  Hari     78

In [9]:
df.loc[101] #Access Specific Columns

Name     Ram
Marks     85
Name: 101, dtype: object

In [10]:
df

     Name  Marks
ID
101   Ram     85
102  Sita     90
103  Hari     78
104  Gita     92

In [11]:
df.loc[101:103, ["Name", "Marks"]]

     Name  Marks
ID
101   Ram     85
102  Sita     90
103  Hari     78

## `iloc` – Integer Position-based Indexing

- `iloc` uses **integer positions**
- Index starts from **0**
- **End value is excluded**
- Similar to Python list slicing

In [12]:
df.set_index("Marks")

       Name
Marks
85      Ram
90     Sita
78     Hari
92     Gita

In [13]:
df

     Name  Marks
ID
101   Ram     85
102  Sita     90
103  Hari     78
104  Gita     92

In [14]:
df.iloc[[0, 2]] #multiple rows

     Name  Marks
ID
101   Ram     85
103  Hari     78

In [15]:
df.iloc[1, 0] #Access Specific Row & Column

'Sita'

In [16]:
df.iloc[0:3, 0:2] #Access Range of Rows & Columns

     Name  Marks
ID
101   Ram     85
102  Sita     90
103  Hari     78

## Comparison Table

| Feature | loc | iloc |
|------|-----|------|
| Type | Label-based | Integer position-based |
| Uses | Index & column names | Row & column numbers |
| Range | End included | End excluded |
| Similar to | Dictionary | Python list |
| Example | df.loc[101] | df.iloc[0] |

### Common Mistakes

❌ Using labels in `iloc`
```python
df.iloc[101]   # Error

df.loc[0]   # KeyError


---

## 📌 10. When to Use What? (Markdown Cell)

```markdown
### When to Use `loc`
- When index has meaningful labels (ID, Name, Date)
- When readability is important

### When to Use `iloc`
- When working with positions
- When index values are unknown
- For fast slicing like arrays