In [1]:
import pandas as pd

df = pd.read_csv("datasets/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
#Single column → Series
df["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [3]:
df[["Name", "Sex", "Age"]]

                                                  Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
886                              Montvila, Rev. Juozas    male  27.0
887                       Graham, Miss. Margaret Edith  female  19.0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN
889                              Behr, Mr. Karl Howell    male  26.0
890                                Dooley, Mr. Patrick    male  32.0

[891 rows x 3 columns]

In [18]:
### .loc — Label-based Selection (VERY IMPORTANT)
#df.loc[row_label, column_label]

Select a single row by label

In [ ]:
df.loc[0]

Select multiple rows

In [ ]:
df.loc[0:4]
#Returns rows from label 0 to 3 (inclusive).

Select specific column

In [22]:
df.loc[:, 'Age']
# All rows, only the 'Age' column.

PassengerId
1      22.0
2      38.0
3      26.0
4      35.0
5      35.0
       ...
887    27.0
888    19.0
889     NaN
890    26.0
891    32.0
Name: Age, Length: 891, dtype: float64

Select specific rows and columns

In [26]:
df.loc[0:2, ['Name', 'Age']]
# Rows 0–2 and only Name & Age columns.

                                                          Name   Age
PassengerId
1                                      Braund, Mr. Owen Harris  22.0
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0

In [27]:
df.loc[0:4]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [28]:
df.loc[0:4, ["Name", "Age", "Sex"]] #Select rows + columns

                                                          Name   Age     Sex
PassengerId
1                                      Braund, Mr. Owen Harris  22.0    male
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
3                                       Heikkinen, Miss. Laina  26.0  female
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female

Boolean condition (very common)

In [30]:
df.loc[df['Age'] > 30] #All rows where Age is greater than 30.

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...
874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Condition + specific column

In [ ]:
df.loc[df['Age'] > 30, 'Name'] #Names of people whose age > 30.

Update values using .loc

In [32]:
df.loc[df['Age'] > 30, 'Age'] = 40
#Changes Age to 40 where Age > 30.

Important notes

.loc uses labels (column names, index names)

Last value in slicing is included

In [34]:
df.loc[0:2]   # includes 0,1,2

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,40.0,1,0,PC 17599,71.2833,C85,C

Difference from .iloc

.loc → label-based

.iloc → position-based

In [36]:
df.loc[3, 'Name']   # by label
df.iloc[0, 0]       # by position

np.int64(0)

In [38]:
df.loc[3, ["Name","Age"]] #Select a single value (cell)

Name    Heikkinen, Miss. Laina
Age                       26.0
Name: 3, dtype: object

In [39]:
# Select all rows but specific columns
df.loc[:, ["Survived", "Pclass", "Fare"]]

             Survived  Pclass     Fare
PassengerId
1                   0       3   7.2500
2                   1       1  71.2833
3                   1       3   7.9250
4                   1       1  53.1000
5                   0       3   8.0500
...               ...     ...      ...
887                 0       2  13.0000
888                 1       1  30.0000
889                 0       3  23.4500
890                 1       1  30.0000
891                 0       3   7.7500

[891 rows x 3 columns]

### .iloc — Position-based Selection

df.iloc[row_position, column_position]

In [40]:
df.iloc[0:5] #Select first 5 rows

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,40.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,40.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,40.0,0,0,373450,8.0500,NaN,S

In [41]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,40.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,40.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,40.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,40.0,0,0,370376,7.7500,NaN,Q

In [42]:
df.iloc[0:5, 0:3] # Select rows & columns by position

,Survived,Pclass,Name
PassengerId,,,
1,0,3,"Braund, Mr. Owen Harris"
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
3,1,3,"Heikkinen, Miss. Laina"
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
5,0,3,"Allen, Mr. William Henry"

Note: GENERALLY USE A LOC INSTEAD OF ILOC

In [43]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,40.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,40.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,40.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,40.0,0,0,370376,7.7500,NaN,Q

In [46]:
print(df.index.name)

PassengerId

In [48]:
# Already index is set to 'PassengerId', so we can use it directly for selection.
df.loc[1] # Select row with index label 1 (PassengerId 1)

df.reset_index(inplace=True) # Now it becomes a column:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [49]:
df.set_index("PassengerId",inplace=True)

In [50]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,40.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,40.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,40.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,40.0,0,0,370376,7.7500,NaN,Q

In [51]:
df.iloc[887]

Survived                               1
Pclass                                 1
Name        Graham, Miss. Margaret Edith
Sex                               female
Age                                 19.0
SibSp                                  0
Parch                                  0
Ticket                            112053
Fare                                30.0
Cabin                                B42
Embarked                               S
Name: 888, dtype: object

In [52]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,40.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,40.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,40.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,40.0,0,0,370376,7.7500,NaN,Q

Since PassengerId is the index:

In [60]:
df.loc[1]                     # Row with PassengerId = 1
print(df)

df.loc[1, "Name"]             # Single value
print("Name" , df)

df.loc[1, ["Name", "Age"]]    # Multiple columns
print(df.loc[1, ["Name", "Age"]])

             Survived  Pclass  \
PassengerId
1                   0       3
2                   1       1
3                   1       3
4                   1       1
5                   0       3
...               ...     ...
887                 0       2
888                 1       1
889                 0       3
890                 1       1
891                 0       3

                                                          Name     Sex   Age  \
PassengerId
1                                      Braund, Mr. Owen Harris    male  22.0
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  40.0
3                                       Heikkinen, Miss. Laina  female  26.0
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  40.0
5                                     Allen, Mr. William Henry    male  40.0
...                                                        ...     ...   ...
887                                      Montvila, Rev. Juozas    male  27.0
888                               Graham, Miss. Margaret Edith  female  19.0
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN
890                                      Behr, Mr. Karl Howell    male  26.0
891                                        Dooley, Mr. Patrick    male  40.0

             SibSp  Parch            Ticket     Fare Cabin Embarked
PassengerId
1                1      0         A/5 21171   7.2500   NaN        S
2                1      0          PC 17599  71.2833   C85        C
3                0      0  STON/O2. 3101282   7.9250   NaN        S
4                1      0            113803  53.1000  C123        S
5                0      0            373450   8.0500   NaN        S
...            ...    ...               ...      ...   ...      ...
887              0      0            211536  13.0000   NaN        S
888              0      0            112053  30.0000   B42        S
889              1      2        W./C. 6607  23.4500   NaN        S
890              0      0            111369  30.0000  C148        C
891              0      0            370376   7.7500   NaN        Q

[891 rows x 11 columns]
Name              Survived  Pclass  \
PassengerId
1                   0       3
2                   1       1
3                   1       3
4                   1       1
5                   0       3
...               ...     ...
887                 0       2
888                 1       1
889                 0       3
890                 1       1
891                 0       3

                                                          Name     Sex   Age  \
PassengerId
1                                      Braund, Mr. Owen Harris    male  22.0
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  40.0
3                                       Heikkinen, Miss. Laina  female  26.0
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  40.0
5                                     Allen, Mr. William Henry    male  40.0
...                                                        ...     ...   ...
887                                      Montvila, Rev. Juozas    male  27.0
888                               Graham, Miss. Margaret Edith  female  19.0
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN
890                                      Behr, Mr. Karl Howell    male  26.0
891                                        Dooley, Mr. Patrick    male  40.0

             SibSp  Parch            Ticket     Fare Cabin Embarked
PassengerId
1                1      0         A/5 21171   7.2500   NaN        S
2                1      0          PC 17599  71.2833   C85        C
3                0      0  STON/O2. 3101282   7.9250   NaN        S
4                1      0            113803  53.1000  C123        S
5                0      0            373450   8.0500   NaN        S
...            ...    ...               ...      ...   ...      ...
887              0      0            211536  13.0000   NaN        S
888              0      0            112053  30.0000   B42        S
889              1      2        W./C. 6607  23.4500   NaN        S
890              0      0            111369  30.0000  C148        C
891              0      0            370376   7.7500   NaN        Q

[891 rows x 11 columns]
Name    Braund, Mr. Owen Harris
Age                        22.0
Name: 1, dtype: object