### Pandas Series

A Series is a one-dimensional labeled array.

Think of it like:

A single column of a table

Or a vector with labels (index)

In [2]:
import pandas as pd

In [3]:
s = pd.Series([10, 20, 30, 40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
#series with custom index
marks = pd.Series([85, 90, 88], index=["Ananda", "Sita", "Ram"])
marks

Ananda    85
Sita      90
Ram       88
dtype: int64

In [5]:
marks[0]

KeyError: 0

# Pandas DataFrame (2-D data)
What is a DataFrame?

A DataFrame is a table (rows + columns), like Excel or SQL table

In [17]:
df = pd.DataFrame({
    "Name": ["Ananda", "Sita", "Ram"],
    "Age": [22, 21, 23],
    "Score": [85, 90,85]
})

df

     Name  Age  Score
0  Ananda   22     85
1    Sita   21     90
2     Ram   23     85

### Select Columns (very important)
#### Single column → Series
### Multiple columns → DataFrame

In [18]:
df["Age"]

0    22
1    21
2    23
Name: Age, dtype: int64

In [19]:
df[["Name", "Score"]]

     Name  Score
0  Ananda     85
1    Sita     90
2     Ram     85

In [20]:
### Now use all the general method for this dataframe like and find first 2 data last two data info and shape
df.head()

     Name  Age  Score
0  Ananda   22     85
1    Sita   21     90
2     Ram   23     85

In [21]:
df.tail(5)

     Name  Age  Score
0  Ananda   22     85
1    Sita   21     90
2     Ram   23     85

In [22]:
df.shape

(3, 3)

In [23]:
df.head(1)

     Name  Age  Score
0  Ananda   22     85

In [24]:
df.sample()

     Name  Age  Score
0  Ananda   22     85

In [25]:
df = pd.DataFrame({
    "Name": [
        "Ananda", "Sita", "Ram", "Gita", "Hari", "Nita", "Ravi", "Pooja", "Kiran", "Maya",
        "Amit", "Sneha", "Rohan", "Anita", "Bikash", "Nisha", "Rahul", "Puja", "Suman", "Kavita",
        "Arjun", "Neha", "Sagar", "Rita", "Manish", "Sunita", "Deepak", "Priya", "Rohit", "Alina",
        "Vikas", "Mina", "Nabin", "Komal", "Dipesh", "Laxmi", "Prakash", "Isha", "Niraj", "Asha",
        "Suraj", "Riya", "Santosh", "Anjali", "Hemant", "Pawan", "Monika", "Ashok", "Preeti", "Sonia"
    ],
    "Age": [
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21,
        23, 20, 22, 21, 23, 20, 22, 21, 23, 20,
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21,
        23, 20, 22, 21, 23, 20, 22, 21, 23, 20,
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21
    ],
    "Score": [
        85, 90, 88, 76, 92, 81, 87, 79, 84, 90,
        86, 78, 91, 83, 89, 80, 88, 82, 90, 77,
        85, 84, 92, 79, 88, 81, 90, 83, 87, 86,
        91, 78, 84, 82, 89, 80, 88, 85, 92, 77,
        90, 83, 91, 79, 86, 84, 88, 81, 90, 85
    ]
})

df

       Name  Age  Score
0    Ananda   22     85
1      Sita   21     90
2       Ram   23     88
3      Gita   20     76
4      Hari   22     92
5      Nita   21     81
6      Ravi   23     87
7     Pooja   20     79
8     Kiran   22     84
9      Maya   21     90
10     Amit   23     86
11    Sneha   20     78
12    Rohan   22     91
13    Anita   21     83
14   Bikash   23     89
15    Nisha   20     80
16    Rahul   22     88
17     Puja   21     82
18    Suman   23     90
19   Kavita   20     77
20    Arjun   22     85
21     Neha   21     84
22    Sagar   23     92
23     Rita   20     79
24   Manish   22     88
25   Sunita   21     81
26   Deepak   23     90
27    Priya   20     83
28    Rohit   22     87
29    Alina   21     86
30    Vikas   23     91
31     Mina   20     78
32    Nabin   22     84
33    Komal   21     82
34   Dipesh   23     89
35    Laxmi   20     80
36  Prakash   22     88
37     Isha   21     85
38    Niraj   23     92
39     Asha   20     77
40    Suraj   22     90
41     Riya   21     83
42  Santosh   23     91
43   Anjali   20     79
44   Hemant   22     86
45    Pawan   21     84
46   Monika   23     88
47    Ashok   20     81
48   Preeti   22     90
49    Sonia   21     85

In [26]:
# save the generated data into local system
df.to_csv('data.csv', index=False)  # index=False avoids adding row numbers

In [27]:
# apply all the analysis like info shape ,describe and others things in your data and find the first 10 and last 10 data 
df.head(10)

     Name  Age  Score
0  Ananda   22     85
1    Sita   21     90
2     Ram   23     88
3    Gita   20     76
4    Hari   22     92
5    Nita   21     81
6    Ravi   23     87
7   Pooja   20     79
8   Kiran   22     84
9    Maya   21     90

In [28]:
df.sample()

      Name  Age  Score
44  Hemant   22     86

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    50 non-null     str
 1   Age     50 non-null     int64
 2   Score   50 non-null     int64
dtypes: int64(2), str(1)
memory usage: 1.3 KB

In [30]:
df.describe()

             Age      Score
count  50.000000  50.000000
mean   21.500000  85.080000
std     1.111168   4.606296
min    20.000000  76.000000
25%    21.000000  81.250000
50%    21.500000  85.000000
75%    22.000000  89.000000
max    23.000000  92.000000

In [32]:
# your task generate the another data using the list

import pandas as pd

# Original data using lists
names = ["Ram", "Shyam", "Hari", "Sita"]
ages = [23, 25, 22, 24]
cities = ["Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur"]

# Create DataFrame
df = pd.DataFrame({
    "Name": names,
    "Age": ages,
    "City": cities
})

print("Original Data:")
print(df)

Original Data:
    Name  Age       City
0    Ram   23  Kathmandu
1  Shyam   25    Pokhara
2   Hari   22   Lalitpur
3   Sita   24  Bhaktapur

### Generate another data column from existing list

Create a new column called "Age_after_5_years"

In [33]:
df["Age_after_5_years"] = [age + 5 for age in ages]

print("\nUpdated Data:")
print(df)

Updated Data:
    Name  Age       City  Age_after_5_years
0    Ram   23  Kathmandu                 28
1  Shyam   25    Pokhara                 30
2   Hari   22   Lalitpur                 27
3   Sita   24  Bhaktapur                 29

Generate a completely new dataset using list

In [34]:
# New list data
products = ["Laptop", "Mouse", "Keyboard", "Monitor"]
prices = [800, 20, 35, 150]
quantity = [5, 50, 30, 10]

df2 = pd.DataFrame({
    "Product": products,
    "Price": prices,
    "Quantity": quantity
})

# Create new calculated column
df2["Total_Value"] = df2["Price"] * df2["Quantity"]

print("\nNew Generated Dataset:")
print(df2)

New Generated Dataset:
    Product  Price  Quantity  Total_Value
0    Laptop    800         5         4000
1     Mouse     20        50         1000
2  Keyboard     35        30         1050
3   Monitor    150        10         1500

Generate random data using list

In [35]:
import random

numbers = [random.randint(1, 100) for _ in range(10)]
df3 = pd.DataFrame({"Random_Numbers": numbers})

print(df3)

   Random_Numbers
0               3
1              93
2              63
3              92
4              40
5              50
6              79
7              35
8              95
9              84

### you can add your own note below using pandas offical documentation https://pandas.pydata.org/docs/

### task find and write the detailed comparison between series and dataframe with code example

Detailed Comparison: Pandas Series vs DataFrame (with Code Examples)
🔹 1) Definition

Series

- A one-dimensional labeled array.
- Like a single column in Excel.
- Holds one type of data (numbers, text, etc.).

DataFrame

- A two-dimensional labeled data structure.
- Like a full Excel table.
- Contains multiple columns (multiple Series combined).

Basic

In [36]:
import pandas as pd

# Series Example
s = pd.Series([10, 20, 30, 40])
print(s)

# DataFrame Example
df = pd.DataFrame({
    "Name": ["Ram", "Shyam", "Hari"],
    "Age": [23, 25, 22]
})
print(df)

0    10
1    20
2    30
3    40
dtype: int64
    Name  Age
0    Ram   23
1  Shyam   25
2   Hari   22

3) Structure Difference

Feature	Series	DataFrame

Dimension	1D	2D

Looks like	Single column	Table

Components	Values + Index	Rows + Columns

Multiple columns	❌ No	✅ Yes

4) Data Representation

Series

In [37]:
s = pd.Series([100, 200, 300], index=["a", "b", "c"])
print(s)

a    100
b    200
c    300
dtype: int64

DataFrame

In [38]:
df = pd.DataFrame({
    "Product": ["Pen", "Book", "Bag"],
    "Price": [10, 50, 500]
})
print(df)

  Product  Price
0     Pen     10
1    Book     50
2     Bag    500

5) How They Are Related

A DataFrame is a collection of Series.

Each column in a DataFrame is a Series.

In [39]:
print(df["Product"])   # This returns a Series

0     Pen
1    Book
2     Bag
Name: Product, dtype: str

6) Data Selection

Series Selection

In [40]:
s = pd.Series([10, 20, 30], index=["x", "y", "z"])
print(s["y"])

20

DataFrame Selection

In [41]:
df = pd.DataFrame({
    "Name": ["Ram", "Hari"],
    "Age": [23, 22]
})

print(df["Name"])     # Column selection
print(df.loc[0])      # Row selection

0     Ram
1    Hari
Name: Name, dtype: str
Name    Ram
Age      23
Name: 0, dtype: object

7) Creation Methods

Series from list

In [42]:
s = pd.Series([1, 2, 3, 4])

DataFrame from dictionary

In [43]:
df = pd.DataFrame({
    "A": [1, 2],
    "B": [3, 4]
})

8) Operations Comparison

Series Math Operation

In [44]:
s = pd.Series([1, 2, 3])
print(s * 2)

0    2
1    4
2    6
dtype: int64

DataFrame Math Operation

In [45]:
df = pd.DataFrame({
    "A": [1, 2],
    "B": [3, 4]
})

print(df * 2)

   A  B
0  2  6
1  4  8

9) Shape Difference

In [46]:
print(s.shape)   # (3,)
print(df.shape)  # (2, 2)

(3,)
(2, 2)

Series → only length

DataFrame → rows × columns

🔹 10) Use Case Difference

Use Series when:

- Working with single column data
- Labels + values needed

Example: temperature list, marks list

Use DataFrame when:

- Working with full dataset
- Multiple columns

Like Excel table / database table

🔹 11) Memory Usage

- Series uses less memory
- DataFrame uses more memory (multiple Series combined)

12) Convert Between Them

Series → DataFrame

In [47]:
s = pd.Series([10, 20, 30])
df = s.to_frame(name="Numbers")
print(df)

   Numbers
0       10
1       20
2       30

DataFrame → Series

In [48]:
print(df["Numbers"])

0    10
1    20
2    30
Name: Numbers, dtype: int64

13) Key Summary Table

Feature	Series	DataFrame

Dimension	1D	2D

Equivalent to	Single column	Full table

Index	Yes	Yes

Columns	No	Yes

Multiple data types	Limited	Yes

Part of	Base object	Collection of Series

14) Real-Life Example

Series

In [49]:
marks = pd.Series([80, 75, 90], index=["Ram", "Shyam", "Hari"])

DataFrame

In [51]:
students = pd.DataFrame({
    "Name": ["Ram", "Shyam", "Hari"],
    "Marks": [80, 75, 90],
    "City": ["KTm", "PKR", "LTP"]
})
print(students)

    Name  Marks City
0    Ram     80  KTm
1  Shyam     75  PKR
2   Hari     90  LTP

🔹 Final Conclusion

Series = Single column

DataFrame = Multiple columns (table)

Every column in DataFrame is a Series

Series is simpler; DataFrame is more powerful and widely used in data science.