In [4]:
import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Age": [22, 19, 25, 21],
    "Marks": [78, 85, 67, 90]
}

df = pd.DataFrame(data)
df

   Name  Age  Marks
0   Ram   22     78
1  Sita   19     85
2  Hari   25     67
3  Gita   21     90

In [5]:
#Sort by Age
df.sort_values(by="Age")

   Name  Age  Marks
1  Sita   19     85
3  Gita   21     90
0   Ram   22     78
2  Hari   25     67

In [6]:
# Sort by Marks (descending)
df.sort_values(by="Marks")

   Name  Age  Marks
2  Hari   25     67
0   Ram   22     78
1  Sita   19     85
3  Gita   21     90

In [7]:
# First by Age, then by Marks
df.sort_values(by=["Age", "Marks"])

   Name  Age  Marks
1  Sita   19     85
3  Gita   21     90
0   Ram   22     78
2  Hari   25     67

In [8]:
df.sort_values(by=["Age", "Marks"], ascending=[True, False])
# Different order for each column:

   Name  Age  Marks
1  Sita   19     85
3  Gita   21     90
0   Ram   22     78
2  Hari   25     67

In [9]:
df.sort_index()
# sort by index

   Name  Age  Marks
0   Ram   22     78
1  Sita   19     85
2  Hari   25     67
3  Gita   21     90

In [10]:
df.sort_index(ascending=False)

   Name  Age  Marks
3  Gita   21     90
2  Hari   25     67
1  Sita   19     85
0   Ram   22     78

In [11]:
df

   Name  Age  Marks
0   Ram   22     78
1  Sita   19     85
2  Hari   25     67
3  Gita   21     90

In [12]:
# Sort and save changes (inplace)
df.sort_values(by="Marks", inplace=True)
df

   Name  Age  Marks
2  Hari   25     67
0   Ram   22     78
1  Sita   19     85
3  Gita   21     90

In [13]:
df

   Name  Age  Marks
2  Hari   25     67
0   Ram   22     78
1  Sita   19     85
3  Gita   21     90

In [14]:
# Sort strings (alphabetical order)
df.sort_values(by="Name")

   Name  Age  Marks
3  Gita   21     90
2  Hari   25     67
0   Ram   22     78
1  Sita   19     85

In [15]:
# Reverse alphabetical:
df.sort_values(by="Name", ascending=False)

   Name  Age  Marks
1  Sita   19     85
0   Ram   22     78
2  Hari   25     67
3  Gita   21     90

## 🧠 Quick Summary

| Task | Method |
|------|--------|
| Sort rows | `sort_values()` |
| Sort index | `sort_index()` |
| Descending order | `ascending=False` |
| Multiple columns | `by=[...]` |
| Save changes | `inplace=True` |
| Fix index | `reset_index(drop=True)` |