In [1]:
import pandas as pd

df = pd.read_csv("datasets/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
#Check original Fare values (before update)
df.loc[df["Survived"] == 1, ["Survived", "Fare"]].head()

   Survived     Fare
1         1  71.2833
2         1   7.9250
3         1  53.1000
8         1  11.1333
9         1  30.0708

In [3]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
# Increase Fare by 10 for survivors
df.loc[df["Survived"] == 1, "Fare"] += 10
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,81.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,17.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,63.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
# Verify update
df.loc[df["Survived"] == 1, ["Survived", "Fare"]].head()

   Survived     Fare
1         1  81.2833
2         1  17.9250
3         1  63.1000
8         1  21.1333
9         1  40.0708

In [6]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,81.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,17.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,63.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,40.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,40.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
# Fill missing Age with 30
df.loc[df["Age"].isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,23.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,17.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,17.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [8]:
df.loc[df["Age"].isna(), "Age"] = 30

In [9]:
# Fill missing Age with 30
df.loc[df["Age"].isna()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [10]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,81.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,17.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,63.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,40.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,30.0,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,40.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [16]:
# your task :Replace Embarked 'S' with 'Southampton'
df.loc[df["Embarked"] == "S", "Embarked"] = "Southampton"
df['Embarked'] = df['Embarked'].replace('S', 'Southampton')

In [17]:
# Increase Age by 1 for male survivors
df.loc[(df["Sex"] == "male") & (df["Survived"] == 1), "Age"] += 1

In [18]:
## your taskSet Fare = 0 for non-survivors in 3rd class
# To set Fare = 0 for passengers who did not survive and were in 3rd class in a pandas DataFrame (Titanic dataset), 
# you can use conditional selection with .loc:
# Set Fare = 0 where Survived = 0 and Pclass = 3
df.loc[(df['Survived'] == 0) & (df['Pclass'] == 3), 'Fare'] = 0

### Explanation:

df['Survived'] == 0 → selects non-survivors

df['Pclass'] == 3 → selects 3rd class passengers

& → combines both conditions

.loc[condition, 'Fare'] = 0 → updates Fare to 0 for those rows

In [19]:
# Update Age and Fare for 1st class passengers
df.loc[df["Pclass"] == 1, ["Age", "Fare"]] = [40, 100]

In [20]:
# Verify multiple column update
df.loc[df["Pclass"] == 1, ["Age", "Fare"]].head()

     Age   Fare
1   40.0  100.0
3   40.0  100.0
6   40.0  100.0
11  40.0  100.0
23  40.0  100.0

In [21]:
# Add 20 Fare to Class 1 and 2 passengers
df.loc[df["Pclass"].isin([1, 2]), "Fare"] += 20

In [22]:
# Verify update
df.loc[df["Pclass"].isin([1, 2]), ["Pclass", "Fare"]].head()

    Pclass      Fare
1        1  120.0000
3        1  120.0000
6        1  120.0000
9        2   60.0708
11       1  120.0000

In [27]:
# Fill missing Cabin with "Unknown"
df['Cabin'] = df['Cabin'].fillna('Unknown')

In [28]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,0.000,Unknown,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,40.0,1,0,PC 17599,120.000,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,17.925,Unknown,Southampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,40.0,1,0,113803,120.000,C123,Southampton
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,0.000,Unknown,Southampton
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,33.000,Unknown,Southampton
887,888,1,1,"Graham, Miss. Margaret Edith",female,40.0,0,0,112053,120.000,B42,Southampton
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,30.0,1,2,W./C. 6607,0.000,Unknown,Southampton
889,890,1,1,"Behr, Mr. Karl Howell",male,40.0,0,0,111369,120.000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,0.000,Unknown,Q

In [29]:
# your task :Replace Embarked 'S' with 'Southampton'
df['Embarked'] = df['Embarked'].replace('Southampton', 'S')

In [30]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,0.000,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,40.0,1,0,PC 17599,120.000,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,17.925,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,40.0,1,0,113803,120.000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,0.000,Unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,33.000,Unknown,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,40.0,0,0,112053,120.000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,30.0,1,2,W./C. 6607,0.000,Unknown,S
889,890,1,1,"Behr, Mr. Karl Howell",male,40.0,0,0,111369,120.000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,0.000,Unknown,Q